version: '2'

services:
  megashop-product:
    container_name: meagashop-service
    build:
      context: .
      dockerfile: ./config/docker/Dockerfile
    env_file: .env
    environment:
      - NODE_ENV=development
    volumes:
      - .:/var/www
    depends_on:
      - postgres
    networks:
      - megashop_network
  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: ./config/docker/Dockerfile.postgres
    networks:
      - megashop_network
  web:
    container_name: nginx
    image: nginx
    volumes:
      - ./config/nginx/megashop.template:/etc/nginx/conf.d/megashop.template
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=http://megashop-product:9000
      - NGINX_PORT=80
    depends_on:
      - megashop-product
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/megashop.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks: 
      - megashop_network

networks:
  megashop_network:
    driver: bridge
